# run parameters
goal_tolerance: 0.3
# run_timeout: 36000.0  
ps_snapshot_period: 10.0
# robot_radius: 0.2 # turtlebot3
# robot_radius: 0.4 # agilex hunter
random_points: 2

# topic names
initial_pose_topic: /initialpose
goal_pose_topic: /move_base/goal
navFnROS_topic: /move_base/NavfnROS/plan
global_planner_topic: /move_base/GlobalPlanner/plan
sbpl_lattice_planner_topic: /move_base/SBPLLatticePlanner/plan
ompl_planner_topic: /move_base/OmplGlobalPlanner/plan 

# action names
navigate_to_pose_action: /move_base

# frame names
fixed_frame: map
child_frame: base_footprint
robot_base_frame: base_link_realistic

# gazebo entity names
robot_entity_name: robot  # base_footprint
