base_global_planner: SBPLLatticePlanner

SBPLLatticePlanner:
  environment_type: XYThetaLattice
#  planner_type: ARAPlanner
  allocated_time: 30.0
  initial_epsilon: 5.0
  forward_search: false
  lethal_obstacle: 250
#  primitive_filename: /home/furkan/turtlebot3_melodic_ws/src/sbpl_lattice_planner/matlab/mprim/unicycle_5cm_expensive_turn_in_place_highcost.mprim

