components_configurations_folder: ~/turtlebot3_melodic_ws/src/global_planning_performance_modelling/config/component_configurations

run_timeout : 36000.0

supervisor_component: global_planning_benchmark_supervisor

components_configuration:
  supervisor: global_planning_benchmark_supervisor/global_planning_benchmark_supervisor.yaml
  move_base: move_base/move_base_tb3.yaml
  move_base_global_planner: move_base/move_base_global_planner_ros.yaml
  rviz: rviz/default_view.rviz

combinatorial_parameters:        #you can write your combinatorial parameters here as an dict in grid_benchmarking.py is taking them
  global_planner_name: [GlobalPlanner]
  use_dijkstra: [true, false]
  lethal_cost: [50, 253]
# etc
