components_configurations_folder: ~/w/catkin_ws/src/global_planning_performance_modelling/config/component_configurations

run_timeout : 36000.0

supervisor_component: global_planning_benchmark_supervisor

components_configuration:
  supervisor: global_planning_benchmark_supervisor/global_planning_benchmark_supervisor.yaml
  move_base: move_base/move_base_tb3.yaml
  move_base_ompl_planner: move_base/move_base_ompl_global_planner.yaml
  rviz: rviz/default_view.rviz

combinatorial_parameters:        #you can write your combinatorial parameters here as an dict in grid_benchmarking.py is taking them
  global_planner_name: [OmplGlobalPlanner]
  planner_type: [RRTStar, RRTConnect, PRMStar]
#  lethal_cost: [50, 253]
# for example you can add local_planner_name: [xx, yy, zz]
