components_configurations_folder: ~/w/catkin_ws/src/global_planning_performance_modelling/config/component_configurations

run_timeout : 36000.0
robot_model_turtlebot3: [[-0.205, -0.155], [-0.205, 0.155], [0.077, 0.155], [0.077, -0.155]]  #for waffle tb3 footprint
robot_model_agilex_hunter: [[-0.165, -0.3725], [-0.165, 0.3725], [0.815, 0.3725], [0.815, -0.3725]]  # for agilex hunter 2.0

supervisor_component: global_planning_benchmark_supervisor
source_workspace_path: ~/w/catkin_ws/src/

components_configuration:
  supervisor: global_planning_benchmark_supervisor/global_planning_benchmark_supervisor.yaml
  move_base: move_base/move_base_tb3.yaml
  move_base_ompl_planner: move_base/move_base_ompl_global_planner.yaml
  rviz: rviz/default_view.rviz

combinatorial_parameters:        #you can write your combinatorial parameters here as an dict in grid_benchmarking.py is taking them
  global_planner_name: [OmplGlobalPlanner]
#  planner_type: [RRTStar, RRTConnect, PRMStar]
  planner_type: [RRTConnect]
  lethal_cost: [150, 200, 253]
  robot_kinematic: [unicycle]
  robot_radius: [0.2]
  robot_major_radius: [0.2]
#  lethal_cost: [50, 253]
# for example you can add local_planner_name: [xx, yy, zz]
