components_configurations_folder: ~/w/catkin_ws/src/global_planning_performance_modelling/config/component_configurations

run_timeout : 36000.0
robot_model_turtlebot3: [[-0.205, -0.155], [-0.205, 0.155], [0.077, 0.155], [0.077, -0.155]]  #for waffle tb3 footprint
robot_model_agilex_hunter: [[-0.165, -0.3725], [-0.165, 0.3725], [0.815, 0.3725], [0.815, -0.3725]]  # for agilex hunter 2.0

sbpl_primitives_path: ~/w/catkin_ws/src/global_planning_performance_modelling/primitives/all_primitives
source_workspace_path: ~/w/catkin_ws/src/
supervisor_component: global_planning_benchmark_supervisor

components_configuration:
  supervisor: global_planning_benchmark_supervisor/global_planning_benchmark_supervisor.yaml
  move_base: move_base/move_base_tb3.yaml
  move_base_global_planner: move_base/move_base_global_planner_ros.yaml
  move_base_sbpl_planner: move_base/move_base_sbpl_lattice_planner.yaml
  move_base_ompl_planner: move_base/move_base_ompl_global_planner.yaml
  rviz: rviz/default_view.rviz

#you can write your combinatorial parameters here as an dict in grid_benchmarking.py is taking them
combinatorial_parameters: [
  {
    global_planner_name: [GlobalPlanner],
    planner_type: [dijkstra, Astar],
    robot_kinematic: [unicycle],
    robot_radius: [0.2],
    robot_major_radius: [0.2],
    lethal_cost: [253],
  },
  {
    global_planner_name: [OmplGlobalPlanner],
    planner_type: [RRTStar, RRTConnect, PRMStar],
    robot_kinematic: [unicycle],
    robot_radius: [0.2],
    robot_major_radius: [0.2],
    lethal_cost: [253],
    time_out: [2.0, 5.0, 10.0],
  },
  { 
    global_planner_name: [SBPLLatticePlanner],
    planner_type: [ADPlanner],    
    robot_kinematic: [unicycle],
    robot_radius: [0.2],
    robot_major_radius: [0.2],
    primitives_per_angle: [7, 9, 11],
    resolution: [0.05],
  },
  { 
    global_planner_name: [SBPLLatticePlanner],
    planner_type: [ADPlanner],
    robot_kinematic: [bicycle],
    robot_radius: [0.4],
    robot_major_radius: [0.65],
    direction: [backwardandforward, onlyforward],
    max_steering_angle: [20, 25, 30, 50],
    resolution: [0.05],
  },
]

#sbpl_primitives_name: [v8_forward_backward_065_15_lin_ang1.mprim, v8_forward_backward_065_15_lin_ang2.mprim, v8_forward_backward_065_25_lin_ang1.mprim, v8_forward_backward_065_25_lin_ang2.mprim, v8_forward_backward_065_50_lin_ang1.mprim, v8_forward_backward_065_50_lin_ang2.mprim ],
# sbpl_primitives_name: [genmprim_unicycle_16_prim7_10.mprim, genmprim_unicycle_16_prim9_10.mprim, genmprim_unicycle_16_prim11_10.mprim
